// <auto-generated />
using Assignment4.Api.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Assignment4.Api.Migrations
{
    [DbContext(typeof(Assignment4DBContext))]
    partial class Assignment4DBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("Assignment4.Api.Entities.ChildSql", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FamilyId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FamilySqlId")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Grade")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FamilySqlId");

                    b.ToTable("ChildrenSql");
                });

            modelBuilder.Entity("Assignment4.Api.Entities.FamilySql", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRegistered")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("FamiliesSql");
                });

            modelBuilder.Entity("Assignment4.Api.Entities.ParentSql", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("FamilyId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FamilySqlId")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FamilySqlId");

                    b.ToTable("ParentsSql");
                });

            modelBuilder.Entity("Assignment4.Api.Entities.ChildSql", b =>
                {
                    b.HasOne("Assignment4.Api.Entities.FamilySql", null)
                        .WithMany("Children")
                        .HasForeignKey("FamilySqlId");
                });

            modelBuilder.Entity("Assignment4.Api.Entities.ParentSql", b =>
                {
                    b.HasOne("Assignment4.Api.Entities.FamilySql", null)
                        .WithMany("Parents")
                        .HasForeignKey("FamilySqlId");
                });

            modelBuilder.Entity("Assignment4.Api.Entities.FamilySql", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Parents");
                });
#pragma warning restore 612, 618
        }
    }
}
