// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WorldCareCenter.Api.Models;

#nullable disable

namespace WorldCareCenter.Api.Migrations.TurkuDB
{
    [DbContext(typeof(TurkuDBContext))]
    [Migration("20241106171744_TurkuDB-data-1")]
    partial class TurkuDBdata1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("WorldCareCenter.Api.Entities.Doctor", b =>
                {
                    b.Property<int>("DoctorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Specialty")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("DoctorID");

                    b.ToTable("Doctors");

                    b.HasData(
                        new
                        {
                            DoctorID = 1,
                            Email = "john.doe@email.com",
                            Name = "John Doe",
                            Specialty = "Neurologist"
                        },
                        new
                        {
                            DoctorID = 2,
                            Email = "smith.bruce@email.com",
                            Name = "Smith Bruce",
                            Specialty = "Psychiatrist"
                        },
                        new
                        {
                            DoctorID = 3,
                            Email = "peter.dam@email.com",
                            Name = "Peter Dam",
                            Specialty = "General Physician"
                        },
                        new
                        {
                            DoctorID = 4,
                            Email = "willaim.john@email.com",
                            Name = "William John",
                            Specialty = "Pediatrician"
                        },
                        new
                        {
                            DoctorID = 5,
                            Email = "amar.micheal@email.com",
                            Name = "Amar Micheal",
                            Specialty = "Dermatologist"
                        },
                        new
                        {
                            DoctorID = 6,
                            Email = "tom.hood@email.com",
                            Name = "Tom Hood",
                            Specialty = "Gynecologist"
                        },
                        new
                        {
                            DoctorID = 7,
                            Email = "joni.bob@email.com",
                            Name = "Joni Bob",
                            Specialty = "Ophthalmologist"
                        });
                });

            modelBuilder.Entity("WorldCareCenter.Api.Entities.Invoice", b =>
                {
                    b.Property<int>("InvoiceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("InvoiceAmount")
                        .HasColumnType("TEXT");

                    b.Property<int>("PatientID")
                        .HasColumnType("INTEGER");

                    b.HasKey("InvoiceID");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("WorldCareCenter.Api.Entities.InvoiceDetail", b =>
                {
                    b.Property<int>("InvoiceDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("InvoiceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InvoiceLineItem")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("InvoiceDetailId");

                    b.ToTable("InvoiceDetails");
                });

            modelBuilder.Entity("WorldCareCenter.Api.Entities.Patient", b =>
                {
                    b.Property<int>("PatientID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PatientFileNo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PatientName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("PatientID");

                    b.ToTable("Patients");
                });
#pragma warning restore 612, 618
        }
    }
}
